version: '3.7'

services:
  front:
    build: ./web
    container_name: test_deploy_web
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./web:/web/
      - staticfiles:/web/static/
    ports:
      - 80:8000
    env_file:
      - ./.env  
    depends_on:
      - db

  db:
    image: postgres
    container_name: test_deploy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    volumes:
      - staticfiles:/web/static/
    ports:
      - 8000:80
    depends_on:
      - front

volumes:
  postgres_data:
  staticfiles:
volumes:
  postgres_data:
  staticfiles:
