name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: compose build(atualizando a cada push)
      run: sudo docker-compose build      
    - uses: actions/checkout@v3   
    - name: compose up
      run: sudo docker-compose up -d
    - uses: actions/checkout@v3
    - name: Sleep for 60 seconds
      run: Start-Sleep -s 60
    - uses: actions/checkout@v3
    - name: dompose down
      run: sudo docker-compose down  
